Repository Worlds-iOS-v2/worlds-ios-fe, pull requests merged in 2025-08, with the labels that each got.

#43 [feat] 카메라 줌, 초점 기능 추가
  worlds-fe-v20/Views/OCR/OCRCameraController.swift
Labels: enhancement

#48 [fix] 세로모드만 지원 가능하도록 설정 변경
  worlds-fe-v20.xcodeproj/project.pbxproj
Labels: bug

#49 [fix] 아이패드의 경우, 화면 회전을 모두 허용해야한다기에... 설정 변경 (아이폰만 세로 모드 지원)
  worlds-fe-v20.xcodeproj/project.pbxproj
Labels: bug

#53 [fix] 번역401에러 -> JWT 인증 헤더 추가
  worlds-fe-v20/Services/APIService.swift
  worlds-fe-v20/Views/QuestionDetailView.swift
Labels: bug

#83 [feat] OCRList 구현
  worlds-fe-v20/Enum/KoreanGrade.swift
  worlds-fe-v20/Enum/RoleGrade.swift
  worlds-fe-v20/Enum/SupportedLanguage.swift
  worlds-fe-v20/Models/OCRListResponse.swift
  worlds-fe-v20/Services/UserAPIManager.swift
  worlds-fe-v20/ViewModels/ChatViewModel.swift
  worlds-fe-v20/ViewModels/MyPageViewModel.swift
  worlds-fe-v20/Views/Chat/ChatDetailView.swift
  worlds-fe-v20/Views/MyPage/MyPageView.swift
  worlds-fe-v20/Views/OCR/OCRCameraController.swift
  worlds-fe-v20/Views/OCR/OCRCameraView.swift
  worlds-fe-v20/Views/OCR/OCRListDetailView.swift
  worlds-fe-v20/Views/OCR/OCRListView.swift
  worlds-fe-v20/Views/OCR/OCRResultView.swift
  worlds-fe-v20/Views/OCR/OCRSummaryModalView.swift
  worlds-fe-v20/Views/Tabbar/CustomTabBarView.swift
Labels: enhancement

#86 [release] 테스트플라이트 배포버전 1.0.6 develop merge
  worlds-fe-v20.xcodeproj/project.pbxproj
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/AppIcon 1.png
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/AppIcon 2.png
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/Contents.json
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/appicon_demo 1.png
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/appicon_demo 2.png
  worlds-fe-v20/Assets.xcassets/AppIcon.appiconset/appicon_demo.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/Contents.json
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/Frame 23.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/Frame 23@2x.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/Frame 23@3x.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/‘camera0821’의 배경이 제거됨 2.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/‘camera0821’의 배경이 제거됨 2@2x.png
  worlds-fe-v20/Assets.xcassets/cameraws.imageset/‘camera0821’의 배경이 제거됨 2@3x.png
  worlds-fe-v20/Info.plist
  worlds-fe-v20/Models/Chat.swift
  worlds-fe-v20/Services/APIService.swift
  worlds-fe-v20/Services/SocketService.swift
  worlds-fe-v20/ViewModels/ChatViewModel.swift
  worlds-fe-v20/ViewModels/SignUpViewModel.swift
  worlds-fe-v20/Views/Chat/AddChatView.swift
  worlds-fe-v20/Views/Chat/ChatDetailView.swift
  worlds-fe-v20/Views/Chat/ChatListView.swift
  worlds-fe-v20/Views/CommentRowView.swift
  worlds-fe-v20/Views/Login/ProfileImageSelectionView.swift
  worlds-fe-v20/Views/QuestionDetailView.swift
Labels: ✅ RELEASE
